[workspace]
members = [
  "fuguex-concrete",

  "fuguex-hooks",
  "fuguex-intrinsics",
  "fuguex-loader",
  "fuguex-machine",
  "fuguex-microx",
  "fuguex-state",
  "fuguex-state-derive",

  "fuguex-core",
]
